[theme]
primaryColor = "#0969DA"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F8FA"
textColor = "#1F2328"
font = "sans serif"
base = "light"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "info"

[ui]
hideTopBar = false
hideFooterMargin = false
density = "expanded"
